# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baea667c0d420d685bde61bf1879e29e7a0759f594360ba99a85ec1746669efdddfcd113cd330299eaed7350b286bfc97932037460f7ea68106ba56e50922953

test:
  secret_key_base: 7501494108f4b8acd74dec5b2a252381eb626770203be458729c103736f9f30703823d0dac88287454551dfb5c218832a77eb3c24081be196503290a81a29abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
